// This file is auto-generated by nestjs-trpc.
// It will be overwritten when the backend starts.
// Placeholder for frontend type imports during initial build.

import { initTRPC } from '@trpc/server';
import { z } from 'zod';
import {
  loginSchema,
  registerSchema,
  createWorkflowSchema,
  updateWorkflowSchema,
  workflowIdSchema,
  triggerEventSchema,
  snoozeEventSchema,
  addCommentSchema,
  paginationSchema,
  eventFilterSchema,
} from '@workflow-manager/shared';

const t = initTRPC.create();

const authRouter = t.router({
  login: t.procedure.input(loginSchema).mutation(() => null as any),
  register: t.procedure.input(registerSchema).mutation(() => null as any),
  refresh: t.procedure
    .input(z.object({ refreshToken: z.string() }))
    .mutation(() => null as any),
  me: t.procedure.query(() => null as any),
});

const workflowsRouter = t.router({
  findAll: t.procedure.input(paginationSchema).query(() => null as any),
  findOne: t.procedure.input(workflowIdSchema).query(() => null as any),
  create: t.procedure.input(createWorkflowSchema).mutation(() => null as any),
  update: t.procedure
    .input(z.object({ id: z.string().cuid(), data: updateWorkflowSchema }))
    .mutation(() => null as any),
  toggleActive: t.procedure.input(workflowIdSchema).mutation(() => null as any),
  delete: t.procedure.input(workflowIdSchema).mutation(() => null as any),
});

const eventsRouter = t.router({
  findAll: t.procedure
    .input(z.object({ pagination: paginationSchema, filters: eventFilterSchema.optional() }))
    .query(() => null as any),
  findOne: t.procedure.input(z.object({ id: z.string() })).query(() => null as any),
  trigger: t.procedure.input(triggerEventSchema).mutation(() => null as any),
  resolve: t.procedure.input(z.object({ id: z.string() })).mutation(() => null as any),
  snooze: t.procedure.input(snoozeEventSchema).mutation(() => null as any),
  addComment: t.procedure.input(addCommentSchema).mutation(() => null as any),
});

const appRouter = t.router({
  auth: authRouter,
  workflows: workflowsRouter,
  events: eventsRouter,
});

export type AppRouter = typeof appRouter;
